  - name: 'Windows: Removendo o Zabbix Agent'
    ansible.windows.win_service:
      name: Zabbix Agent
      state: absent

  - name: "Windows | Configurando path zabbix.exe"
    ansible.windows.win_file:
      path: 'C:\Zabbix2\'
      state: directory

  - name: "Windows | Baixando o pacote (agent 2)"
    ansible.windows.win_get_url:
      url: https://cdn.zabbix.com/zabbix/binaries/stable/6.0/6.0.6/zabbix_agent2-6.0.6-windows-amd64-openssl-static.zip
      dest: C:\Zabbix2\zabbix_agent2-6.0.6-windows-amd64-openssl-static.zip
      force: false
      follow_redirects: all

  - name: "Windows | Descompactando o arquivo"
    community.windows.win_unzip:
      src: C:\Zabbix2\zabbix_agent2-6.0.6-windows-amd64-openssl-static.zip
      dest: C:\Zabbix2
      creates: C:\Zabbix2\bin\zabbix_agent2.exe

  - name: "Windows | Limpando o download do Zabbix Agent Zip"
    ansible.windows.win_file:
      path: C:\Zabbix2\zabbix_agent2-6.0.6-windows-amd64-openssl-static.zip
      state: absent

  - name: "Windows | Verificando se o serviço existe"
    ansible.windows.win_service:
      name: "Zabbix Agent 2"
    register: zabbix_windows_service

  - name: "Windows | Registrando o serviço"
    ansible.windows.win_command: '"C:\Zabbix2\bin\zabbix_agent2.exe" --config "C:\Zabbix2\conf\zabbix_agent2.conf" --install'
    when: not zabbix_windows_service.exists