---
- name: Deploy do Zabbix Agent2
  hosts: "{{ grupo }}"
  become: true
  vars:
    - zabbix_major_version: 6.0
    - zabbix_full_version: 6.0-1
    - server: 
  
  roles:
    - zabbixagent

  post_tasks:
    - include_role:
        name: zabbixagent
        tasks_from: config.yml