---
- name: Deploy do Zabbix Agent2
  hosts: all
  become: true
  #gather_facts: true
  vars:
    - zabbix_major_version: 6.0
    - zabbix_full_version: 6.0-1
    - server: 
    - serveractive: 
  
  roles:
    - zabbix_agent

  post_tasks:
    - include_role:
        name: zabbix_agent
        tasks_from: config.yml
