- name: 'Iniciando deploy do Zabbix-Agent2 | Sistema Operacional: {{ansible_os_family}} - {{ansible_distribution}} - {{ansible_distribution_major_version}}'
  include_tasks: rhel.yml
  when:  ansible_os_family == "RedHat"

- name: 'Iniciando deploy do Zabbix-Agent2 | Sistema Operacional: {{ansible_os_family}} - {{ansible_distribution}} - {{ansible_distribution_major_version}}'
  include_tasks: ubuntu_debian.yml
  when:  ansible_os_family == "Debian" or ansible_os_family == "Ubuntu"

- name: 'Iniciando deploy do Zabbix-Agent2 | Sistema Operacional: Windows'
  include_tasks: windows.yml
  when:  ansible_os_family == "Windows"