  - name: 'Colocando o Selinux em modo permissive'
    selinux:
      policy: targeted
      state: permissive

  - name: 'Removendo Zabbix Agent antigo'
    become: true
    yum:
      name:
        - zabbix-agent
      state: absent 
     

  - name: 'Baixando o pacote do Zabbix {{ zabbix_major_version }} | Sistema Operacional: {{ansible_distribution}} - {{ansible_distribution_major_version}}'
    yum:
      disable_gpg_check: true
      name: 'https://repo.zabbix.com/zabbix/{{ zabbix_major_version }}/rhel/{{ansible_distribution_major_version}}/x86_64/zabbix-release-{{ zabbix_full_version }}.el{{ansible_distribution_major_version}}.noarch.rpm'
      state: present
 
  - name: 'Instalando Zabbix Agent2 | Sistema Operacional: {{ansible_distribution}} - {{ansible_distribution_major_version}}'
    yum:
     name:
        - zabbix-agent2
        - zabbix-get
        - zabbix-sender 

  - name: 'Liberando as portas no firewalld'
    firewalld:
      port: 10050/tcp
      permanent: yes
      state: enabled
  
  - name: 'Reiniciando o firewalld'
    systemd:
      name: firewalld
      state: reloaded
      enabled: yes 

  - name: 'Iniciando o serviço do Zabbix-Agent2'
    ansible.builtin.service:
        name: zabbix-agent2
        state: started
